ASFLAGS_ADDITIONAL = 
XILINX_ARM_CROSS_COMPILE = F:/Xilinx2/SDK/2017.2/gnu/arm/nt/bin
TARGET_SYSROOT = C:/PROGRA~3/MATLAB/SUPPOR~1/R2018a/3P778C~1.INS/ZYNQLI~1.INS/sysroot
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2018a/toolbox/target/SUPPOR~1/zynq
STACK_SIZE = 64
