SLStudio.Utils.RemoveHighlighting(get_param('Dynamic_Calculations', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_Dynamic_Calculations', 'handle'));
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation', 1, 7, '');
annotate_port('gm_Dynamic_Calculations/Signal Scaling  & Casting', 0, 7, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Delay', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Add', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Add', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/dt^2', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Add', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Switch', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator/Product', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator/Product1', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, '');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, '');
annotate_port('gm_Dynamic_Calculations/Signal Scaling  & Casting/Gain6', 0, 1, '');
annotate_port('gm_Dynamic_Calculations/Signal Scaling  & Casting/Cast6', 0, 1, '');
