open_system('gm_Dynamic_Calculations');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation', 1, 7, 'cp : 21.472 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/Signal Scaling  & Casting', 'user2');
annotate_port('gm_Dynamic_Calculations/Signal Scaling  & Casting', 0, 7, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation', 1, 1, 'cp : 21.472 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator', 0, 1, 'cp : 12.697 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time', 0, 1, 'cp : 15.015 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Delay', 'user1');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Delay', 1, 1, 'cp : 21.472 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/dt^2', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/dt^2', 0, 1, 'cp : 21.442 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Add', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Add', 0, 1, 'cp : 15.015 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Switch', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Switch', 0, 1, 'cp : 13.755 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator/Product', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator/Product', 0, 1, 'cp : 12.697 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator/Product1', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/TimeGenerator/Product1', 0, 1, 'cp : 6.427 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/Signal Scaling  & Casting/Gain6', 'user1');
annotate_port('gm_Dynamic_Calculations/Signal Scaling  & Casting/Gain6', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/Signal Scaling  & Casting/Cast6', 'user2');
annotate_port('gm_Dynamic_Calculations/Signal Scaling  & Casting/Cast6', 0, 1, 'cp : 0 ns');
