-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\AWFG_Phase2\Difference_Time.vhd
-- Created: 2018-08-30 01:10:44
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Difference_Time
-- Source Path: Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Difference_Time IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Time_rsvd                         :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
        breakpoints                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        dt                                :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En19
        );
END Difference_Time;


ARCHITECTURE rtl OF Difference_Time IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL Time_signed                      : signed(26 DOWNTO 0);  -- sfix27_En19
  SIGNAL breakpoints_unsigned             : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Detect_Change_u_d                : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL Detect_Change_out1               : std_logic;
  SIGNAL Switch_out1                      : signed(26 DOWNTO 0);  -- sfix27_En19
  SIGNAL Delay_out1                       : signed(26 DOWNTO 0);  -- sfix27_En19
  SIGNAL Add_sub_cast                     : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Add_sub_cast_1                   : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Add_sub_temp                     : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Add_out1                         : signed(26 DOWNTO 0);  -- sfix27_En19

BEGIN
  -- Time Difference (x - x0)

  Time_signed <= signed(Time_rsvd);

  breakpoints_unsigned <= unsigned(breakpoints);

  Detect_Change_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Detect_Change_u_d <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Detect_Change_u_d <= breakpoints_unsigned;
      END IF;
    END IF;
  END PROCESS Detect_Change_process;

  Detect_Change_out1 <= hdlcoder_to_stdlogic(Detect_Change_u_d /= breakpoints_unsigned);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(16#0000000#, 27);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  
  Switch_out1 <= Delay_out1 WHEN Detect_Change_out1 = '0' ELSE
      Time_signed;

  Add_sub_cast <= resize(Time_signed, 32);
  Add_sub_cast_1 <= resize(Switch_out1, 32);
  Add_sub_temp <= Add_sub_cast - Add_sub_cast_1;
  Add_out1 <= Add_sub_temp(26 DOWNTO 0);

  dt <= std_logic_vector(Add_out1);

END rtl;

