-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\AWFG_Phase2\Dynamic_Calculations_pkg.vhd
-- Created: 2018-08-30 01:10:44
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Dynamic_Calculations_pkg IS
  TYPE vector_of_signed27 IS ARRAY (NATURAL RANGE <>) OF signed(26 DOWNTO 0);
END Dynamic_Calculations_pkg;

