vlib work
vmap -c
vcom  Dynamic_Calculations_pkg.vhd
vcom  Difference_Time.vhd
vcom  Polynomial_Calculation.vhd
vcom  TimeGenerator.vhd
vcom  SinglePortRAM_generic.vhd
vcom  Write_to_Memory.vhd
vcom  FPGA_Calculation.vhd
vcom  Signal_Scaling_Casting.vhd
vcom  Dynamic_Calculations.vhd
