-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\AWFG_Phase2\Dynamic_Calculations.vhd
-- Created: 2018-08-30 01:10:44
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- y                             ce_out        1e-08
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Dynamic_Calculations
-- Source Path: Dynamic_Calculations
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Dynamic_Calculations IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        c0                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        c1                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        c2                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        write                             :   IN    std_logic;
        writeAddr                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        M                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        T                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ce_out                            :   OUT   std_logic;
        y                                 :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En19
        );
END Dynamic_Calculations;


ARCHITECTURE rtl OF Dynamic_Calculations IS

  -- Component Declarations
  COMPONENT Signal_Scaling_Casting
    PORT( c0                              :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          c1                              :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          c2                              :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          write                           :   IN    std_logic;
          writeAddr                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          M                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          T                               :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          c0i                             :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          c1i                             :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          c2i                             :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          writei                          :   OUT   std_logic;
          writeAddri                      :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Mi                              :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          Ti                              :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En19
          );
  END COMPONENT;

  COMPONENT FPGA_Calculation
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          c0                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          c1                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          c2                              :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          write                           :   IN    std_logic;
          writeAddr                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          M                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          T                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
          y                               :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En19
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Signal_Scaling_Casting
    USE ENTITY work.Signal_Scaling_Casting(rtl);

  FOR ALL : FPGA_Calculation
    USE ENTITY work.FPGA_Calculation(rtl);

  -- Signals
  SIGNAL Signal_Scaling_Casting_out1      : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL Signal_Scaling_Casting_out2      : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL Signal_Scaling_Casting_out3      : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL Signal_Scaling_Casting_out4      : std_logic;
  SIGNAL Signal_Scaling_Casting_out5      : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Signal_Scaling_Casting_out6      : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL Signal_Scaling_Casting_out7      : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FPGA_Calculation_out1            : std_logic_vector(26 DOWNTO 0);  -- ufix27

BEGIN
  -- AWFG MODEL FPGA BLOCK

  u_Signal_Scaling_Casting : Signal_Scaling_Casting
    PORT MAP( c0 => c0,  -- int32
              c1 => c1,  -- int32
              c2 => c2,  -- int32
              write => write,
              writeAddr => writeAddr,  -- uint8
              M => M,  -- int32
              T => T,  -- uint32
              c0i => Signal_Scaling_Casting_out1,  -- sfix27_En19
              c1i => Signal_Scaling_Casting_out2,  -- sfix27_En19
              c2i => Signal_Scaling_Casting_out3,  -- sfix27_En19
              writei => Signal_Scaling_Casting_out4,
              writeAddri => Signal_Scaling_Casting_out5,  -- uint8
              Mi => Signal_Scaling_Casting_out6,  -- sfix27_En19
              Ti => Signal_Scaling_Casting_out7  -- sfix27_En19
              );

  u_FPGA_Calculation : FPGA_Calculation
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              c0 => Signal_Scaling_Casting_out1,  -- sfix27_En19
              c1 => Signal_Scaling_Casting_out2,  -- sfix27_En19
              c2 => Signal_Scaling_Casting_out3,  -- sfix27_En19
              write => Signal_Scaling_Casting_out4,
              writeAddr => Signal_Scaling_Casting_out5,  -- uint8
              M => Signal_Scaling_Casting_out6,  -- sfix27_En19
              T => Signal_Scaling_Casting_out7,  -- sfix27_En19
              y => FPGA_Calculation_out1  -- sfix27_En19
              );

  ce_out <= clk_enable;

  y <= FPGA_Calculation_out1;

END rtl;

