open_system('Dynamic_Calculations');
open_system('gm_Dynamic_Calculations');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Add', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Add', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Add', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Add', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Polynomial_Calculation/Difference_Time/Detect Change', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 'user2');
annotate_port('gm_Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, 'Block not characterized');
hilite_system('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 'user2');
annotate_port('Dynamic_Calculations/FPGA_Calculation/Write_to_Memory/Single Port RAM2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
