-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\AWFG_Phase2\Signal_Scaling_Casting.vhd
-- Created: 2018-08-30 01:10:44
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Signal_Scaling_Casting
-- Source Path: Dynamic_Calculations/Signal Scaling  & Casting
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Signal_Scaling_Casting IS
  PORT( c0                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        c1                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        c2                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        write                             :   IN    std_logic;
        writeAddr                         :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        M                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        T                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        c0i                               :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
        c1i                               :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
        c2i                               :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
        writei                            :   OUT   std_logic;
        writeAddri                        :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Mi                                :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En19
        Ti                                :   OUT   std_logic_vector(26 DOWNTO 0)  -- sfix27_En19
        );
END Signal_Scaling_Casting;


ARCHITECTURE rtl OF Signal_Scaling_Casting IS

  -- Signals
  SIGNAL c0_signed                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain9_out1                       : signed(63 DOWNTO 0);  -- sfix64_En46
  SIGNAL Cast_out1                        : signed(26 DOWNTO 0);  -- sfix27_En19
  SIGNAL c1_signed                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain8_out1                       : signed(63 DOWNTO 0);  -- sfix64_En46
  SIGNAL Cast1_out1                       : signed(26 DOWNTO 0);  -- sfix27_En19
  SIGNAL c2_signed                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain7_out1                       : signed(63 DOWNTO 0);  -- sfix64_En46
  SIGNAL Cast2_out1                       : signed(26 DOWNTO 0);  -- sfix27_En19
  SIGNAL Gain3_out1                       : unsigned(7 DOWNTO 0);  -- ufix8_En7
  SIGNAL Cast4_out1                       : std_logic;
  SIGNAL writeAddr_unsigned               : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain4_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En7
  SIGNAL Cast5_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL M_signed                         : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain5_out1                       : signed(63 DOWNTO 0);  -- sfix64_En46
  SIGNAL Cast3_out1                       : signed(26 DOWNTO 0);  -- sfix27_En19
  SIGNAL T_unsigned                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Gain6_out1                       : unsigned(63 DOWNTO 0);  -- ufix64_En47
  SIGNAL Cast6_out1                       : signed(26 DOWNTO 0);  -- sfix27_En19

BEGIN
  -- Data Casting and Scaling

  c0_signed <= signed(c0);

  Gain9_out1 <= resize(c0_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);

  Cast_out1 <= Gain9_out1(53 DOWNTO 27);

  c0i <= std_logic_vector(Cast_out1);

  c1_signed <= signed(c1);

  Gain8_out1 <= resize(c1_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);

  Cast1_out1 <= Gain8_out1(53 DOWNTO 27);

  c1i <= std_logic_vector(Cast1_out1);

  c2_signed <= signed(c2);

  Gain7_out1 <= resize(c2_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);

  Cast2_out1 <= Gain7_out1(53 DOWNTO 27);

  c2i <= std_logic_vector(Cast2_out1);

  Gain3_out1 <= unsigned'(write & '0' & '0' & '0' & '0' & '0' & '0' & '0');

  
  Cast4_out1 <= '1' WHEN Gain3_out1 /= to_unsigned(16#00#, 8) ELSE
      '0';

  writei <= Cast4_out1;

  writeAddr_unsigned <= unsigned(writeAddr);

  Gain4_out1 <= resize(writeAddr_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0', 16);

  Cast5_out1 <= Gain4_out1(14 DOWNTO 7);

  writeAddri <= std_logic_vector(Cast5_out1);

  M_signed <= signed(M);

  Gain5_out1 <= resize(M_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);

  Cast3_out1 <= Gain5_out1(53 DOWNTO 27);

  Mi <= std_logic_vector(Cast3_out1);

  T_unsigned <= unsigned(T);

  Gain6_out1 <= resize(T_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);

  Cast6_out1 <= signed(Gain6_out1(54 DOWNTO 28));

  Ti <= std_logic_vector(Cast6_out1);

END rtl;

