-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\uc3_preparation1_2017\CandHDL_hdl.vhd
-- Created: 2018-08-28 20:42:58
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2e-05
-- Target subsystem base rate: 2e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- (no clock)    0
-- ce_out        2e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- LD0                           ce_out        2e-05
-- LD1                           (no clock)    inf
-- LD2                           (no clock)    inf
-- LD3                           (no clock)    inf
-- duty1                         ce_out        2e-05
-- duty2                         (no clock)    inf
-- duty3                         (no clock)    inf
-- duty4                         (no clock)    inf
-- duty5                         (no clock)    inf
-- duty6                         (no clock)    inf
-- duty7                         (no clock)    inf
-- duty8                         (no clock)    inf
-- Digital_out                   ce_out        2e-05
-- Probes_sig1                   (no clock)    inf
-- Probes_sig2                   (no clock)    inf
-- Probes_sig3                   ce_out        2e-05
-- Probes_sig4                   (no clock)    inf
-- Probes_sig5                   (no clock)    inf
-- Probes_sig6                   (no clock)    inf
-- Probes_sig7                   (no clock)    inf
-- Probes_sig8                   (no clock)    inf
-- shared_signals_out_sig1       (no clock)    inf
-- shared_signals_out_sig2       (no clock)    inf
-- shared_signals_out_sig3       ce_out        2e-05
-- shared_signals_out_sig4       (no clock)    inf
-- shared_signals_out_sig5       (no clock)    inf
-- shared_signals_out_sig6       (no clock)    inf
-- shared_signals_out_sig7       (no clock)    inf
-- shared_signals_out_sig8       (no clock)    inf
-- shared_signals_out_sig9       (no clock)    inf
-- shared_signals_out_sig10      (no clock)    inf
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CandHDL_hdl
-- Source Path: uc3_preparation1_2017/CandHDL_hdl
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CandHDL_hdl IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        BTN0                              :   IN    std_logic;
        BTN1                              :   IN    std_logic;
        BTN2                              :   IN    std_logic;
        BTN3                              :   IN    std_logic;
        SW0                               :   IN    std_logic;
        SW1                               :   IN    std_logic;
        SW2                               :   IN    std_logic;
        SW3                               :   IN    std_logic;
        AD6                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AD7                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AD14                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AD15                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Digital_in                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Tune_param_sig1                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Tune_param_sig2                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Tune_param_sig3                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Tune_param_sig4                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Tune_param_sig5                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Tune_param_sig6                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Tune_param_sig7                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Tune_param_sig8                   :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig1            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig2            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig3            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig4            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig5            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig6            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig7            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig8            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig9            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig10           :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        ce_out                            :   OUT   std_logic;
        LD0                               :   OUT   std_logic;
        LD1                               :   OUT   std_logic;
        LD2                               :   OUT   std_logic;
        LD3                               :   OUT   std_logic;
        duty1                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty2                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty3                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty4                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty5                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty6                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty7                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty8                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        Digital_out                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Probes_sig1                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        Probes_sig2                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        Probes_sig3                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        Probes_sig4                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        Probes_sig5                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        Probes_sig6                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        Probes_sig7                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        Probes_sig8                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig1           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig2           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig3           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig4           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig5           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig6           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig7           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig8           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig9           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig10          :   OUT   std_logic_vector(31 DOWNTO 0)  -- int32
        );
END CandHDL_hdl;


ARCHITECTURE rtl OF CandHDL_hdl IS

  -- Component Declarations
  COMPONENT hdlgenerate
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          BTN0                            :   IN    std_logic;
          BTN1                            :   IN    std_logic;
          BTN2                            :   IN    std_logic;
          BTN3                            :   IN    std_logic;
          SW0                             :   IN    std_logic;
          SW1                             :   IN    std_logic;
          SW2                             :   IN    std_logic;
          SW3                             :   IN    std_logic;
          AD6                             :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AD7                             :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AD14                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          AD15                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Digital_in                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          tune_w0000                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          tune_w0001                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          tune_w0002                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          tune_w0003                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          tune_w0004                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          tune_w0005                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          tune_w0006                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          tune_w0007                      :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig1          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig2          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig3          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig4          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig5          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig6          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig7          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig8          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig9          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_in_sig10         :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          LD0                             :   OUT   std_logic;
          LD1                             :   OUT   std_logic;
          LD2                             :   OUT   std_logic;
          LD3                             :   OUT   std_logic;
          duty1                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          duty2                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          duty3                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          duty4                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          duty5                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          duty6                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          duty7                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          duty8                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          Digital_out                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          probe_r0100                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          probe_r0101                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          probe_r0102                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          probe_r0103                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          probe_r0104                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          probe_r0105                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          probe_r0106                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          probe_r0107                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig1         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig2         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig3         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig4         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig5         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig6         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig7         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig8         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig9         :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
          shared_signals_out_sig10        :   OUT   std_logic_vector(31 DOWNTO 0)  -- int32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : hdlgenerate
    USE ENTITY work.hdlgenerate(rtl);

  -- Signals
  SIGNAL hdlgenerate_out1                 : std_logic;
  SIGNAL hdlgenerate_out2                 : std_logic;
  SIGNAL hdlgenerate_out3                 : std_logic;
  SIGNAL hdlgenerate_out4                 : std_logic;
  SIGNAL hdlgenerate_out5                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL hdlgenerate_out6                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL hdlgenerate_out7                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL hdlgenerate_out8                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL hdlgenerate_out9                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL hdlgenerate_out10                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL hdlgenerate_out11                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL hdlgenerate_out12                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL y                                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL hdlgenerate_out14                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_out1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL hdlgenerate_out16                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL hdlgenerate_out17                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL hdlgenerate_out18                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL hdlgenerate_out19                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL hdlgenerate_out20                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL hdlgenerate_out21                : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in1                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in2                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in3                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in4                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in5                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in6                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in7                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in8                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in9                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL share_in10                       : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_hdlgenerate : hdlgenerate
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              BTN0 => BTN0,
              BTN1 => BTN1,
              BTN2 => BTN2,
              BTN3 => BTN3,
              SW0 => SW0,
              SW1 => SW1,
              SW2 => SW2,
              SW3 => SW3,
              AD6 => AD6,  -- uint16
              AD7 => AD7,  -- uint16
              AD14 => AD14,  -- uint16
              AD15 => AD15,  -- uint16
              Digital_in => Digital_in,  -- uint8
              tune_w0000 => Tune_param_sig1,  -- int32
              tune_w0001 => Tune_param_sig2,  -- int32
              tune_w0002 => Tune_param_sig3,  -- int32
              tune_w0003 => Tune_param_sig4,  -- int32
              tune_w0004 => Tune_param_sig5,  -- int32
              tune_w0005 => Tune_param_sig6,  -- int32
              tune_w0006 => Tune_param_sig7,  -- int32
              tune_w0007 => Tune_param_sig8,  -- int32
              shared_signals_in_sig1 => shared_signals_in_sig1,  -- int32
              shared_signals_in_sig2 => shared_signals_in_sig2,  -- int32
              shared_signals_in_sig3 => shared_signals_in_sig3,  -- int32
              shared_signals_in_sig4 => shared_signals_in_sig4,  -- int32
              shared_signals_in_sig5 => shared_signals_in_sig5,  -- int32
              shared_signals_in_sig6 => shared_signals_in_sig6,  -- int32
              shared_signals_in_sig7 => shared_signals_in_sig7,  -- int32
              shared_signals_in_sig8 => shared_signals_in_sig8,  -- int32
              shared_signals_in_sig9 => shared_signals_in_sig9,  -- int32
              shared_signals_in_sig10 => shared_signals_in_sig10,  -- int32
              LD0 => hdlgenerate_out1,
              LD1 => hdlgenerate_out2,
              LD2 => hdlgenerate_out3,
              LD3 => hdlgenerate_out4,
              duty1 => hdlgenerate_out5,  -- uint16
              duty2 => hdlgenerate_out6,  -- uint16
              duty3 => hdlgenerate_out7,  -- uint16
              duty4 => hdlgenerate_out8,  -- uint16
              duty5 => hdlgenerate_out9,  -- uint16
              duty6 => hdlgenerate_out10,  -- uint16
              duty7 => hdlgenerate_out11,  -- uint16
              duty8 => hdlgenerate_out12,  -- uint16
              Digital_out => y,  -- uint8
              probe_r0100 => hdlgenerate_out14,  -- int32
              probe_r0101 => share_out1,  -- int32
              probe_r0102 => hdlgenerate_out16,  -- int32
              probe_r0103 => hdlgenerate_out17,  -- int32
              probe_r0104 => hdlgenerate_out18,  -- int32
              probe_r0105 => hdlgenerate_out19,  -- int32
              probe_r0106 => hdlgenerate_out20,  -- int32
              probe_r0107 => hdlgenerate_out21,  -- int32
              shared_signals_out_sig1 => share_in1,  -- int32
              shared_signals_out_sig2 => share_in2,  -- int32
              shared_signals_out_sig3 => share_in3,  -- int32
              shared_signals_out_sig4 => share_in4,  -- int32
              shared_signals_out_sig5 => share_in5,  -- int32
              shared_signals_out_sig6 => share_in6,  -- int32
              shared_signals_out_sig7 => share_in7,  -- int32
              shared_signals_out_sig8 => share_in8,  -- int32
              shared_signals_out_sig9 => share_in9,  -- int32
              shared_signals_out_sig10 => share_in10  -- int32
              );

  ce_out <= clk_enable;

  LD0 <= hdlgenerate_out1;

  LD1 <= hdlgenerate_out2;

  LD2 <= hdlgenerate_out3;

  LD3 <= hdlgenerate_out4;

  duty1 <= hdlgenerate_out5;

  duty2 <= hdlgenerate_out6;

  duty3 <= hdlgenerate_out7;

  duty4 <= hdlgenerate_out8;

  duty5 <= hdlgenerate_out9;

  duty6 <= hdlgenerate_out10;

  duty7 <= hdlgenerate_out11;

  duty8 <= hdlgenerate_out12;

  Digital_out <= y;

  Probes_sig1 <= hdlgenerate_out14;

  Probes_sig2 <= share_out1;

  Probes_sig3 <= hdlgenerate_out16;

  Probes_sig4 <= hdlgenerate_out17;

  Probes_sig5 <= hdlgenerate_out18;

  Probes_sig6 <= hdlgenerate_out19;

  Probes_sig7 <= hdlgenerate_out20;

  Probes_sig8 <= hdlgenerate_out21;

  shared_signals_out_sig1 <= share_in1;

  shared_signals_out_sig2 <= share_in2;

  shared_signals_out_sig3 <= share_in3;

  shared_signals_out_sig4 <= share_in4;

  shared_signals_out_sig5 <= share_in5;

  shared_signals_out_sig6 <= share_in6;

  shared_signals_out_sig7 <= share_in7;

  shared_signals_out_sig8 <= share_in8;

  shared_signals_out_sig9 <= share_in9;

  shared_signals_out_sig10 <= share_in10;

END rtl;

