-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\uc3_preparation1_2017\CandHDL_hdl_pkg.vhd
-- Created: 2018-08-28 20:42:58
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE CandHDL_hdl_pkg IS
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
END CandHDL_hdl_pkg;

