SLStudio.Utils.RemoveHighlighting(get_param('uc3_preparation1_2017', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_uc3_preparation1_2017', 'handle'));
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate', 1, 28, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation', 1, 2, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part', 1, 6, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator', 0, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/Gain1', 0, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Delay1', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM', 1, 1, '');
annotate_port('uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM', 1, 1, '');
annotate_port('uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM1', 1, 1, '');
annotate_port('uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM1', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM1', 1, 1, '');
annotate_port('uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM1', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM2', 1, 1, '');
annotate_port('uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM2', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM2', 1, 1, '');
annotate_port('uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Single Port RAM2', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Subtract', 0, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Switch1', 0, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/adding_all the terms', 1, 1, '');
annotate_port('uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/adding_all the terms', 1, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator/Product', 0, 1, '');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator/Product1', 0, 1, '');
