open_system('gm_uc3_preparation1_2017');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate', 1, 28, 'cp : 15.467 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation', 1, 2, 'cp : 15.467 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part', 1, 6, 'cp : 15.467 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator', 0, 1, 'cp : 13.013 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/Gain1', 'user1');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/Gain1', 0, 1, 'cp : 0 ns');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'blue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Delay1', 'user1');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Delay1', 1, 1, 'cp : 15.467 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Subtract', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Subtract', 0, 1, 'cp : 15.437 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Switch1', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/ FPGA_Part/Switch1', 0, 1, 'cp : 14.071 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator/Product', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator/Product', 0, 1, 'cp : 13.013 ns');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'lightblue';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator/Product1', 'user2');
annotate_port('gm_uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator/Product1', 0, 1, 'cp : 6.585 ns');
