-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\uc3_preparation1_2017\FPGA_simulation.vhd
-- Created: 2018-08-28 20:42:58
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FPGA_simulation
-- Source Path: uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FPGA_simulation IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        M                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        T                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Cc0                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Cc1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Cc2                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        Count_out                         :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        we                                :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END FPGA_simulation;


ARCHITECTURE rtl OF FPGA_simulation IS

  -- Component Declarations
  COMPONENT TimeGenerator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          M                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En19
          T                               :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En19
          Time_rsvd                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En19
          read_add                        :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  COMPONENT alphaFPGA_Part
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Cc0                             :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Cc1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Cc2                             :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Counter_out_write_addr          :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          We_write_enable                 :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Time_rsvd                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En19
          read_rsvd                       :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          output_wave_y                   :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : TimeGenerator
    USE ENTITY work.TimeGenerator(rtl);

  FOR ALL : alphaFPGA_Part
    USE ENTITY work.alphaFPGA_Part(rtl);

  -- Signals
  SIGNAL M_signed                         : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain_cast                        : signed(63 DOWNTO 0);  -- sfix64_En50
  SIGNAL Gain_out1                        : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL T_signed                         : signed(31 DOWNTO 0);  -- int32
  SIGNAL Gain1_cast                       : signed(63 DOWNTO 0);  -- sfix64_En50
  SIGNAL Gain1_out1                       : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Time_rsvd                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL TimeGenerator_out2               : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL alphaFPGA_Part_out1              : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_TimeGenerator : TimeGenerator
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              M => std_logic_vector(Gain_out1),  -- sfix32_En19
              T => std_logic_vector(Gain1_out1),  -- sfix32_En19
              Time_rsvd => Time_rsvd,  -- sfix32_En19
              read_add => TimeGenerator_out2  -- uint8
              );

  u_FPGA_Part : alphaFPGA_Part
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Cc0 => Cc0,  -- int32
              Cc1 => Cc1,  -- int32
              Cc2 => Cc2,  -- int32
              Counter_out_write_addr => Count_out,  -- int32
              We_write_enable => we,  -- int32
              Time_rsvd => Time_rsvd,  -- sfix32_En19
              read_rsvd => TimeGenerator_out2,  -- uint8
              output_wave_y => alphaFPGA_Part_out1  -- uint16
              );

  M_signed <= signed(M);

  Gain_cast <= resize(M_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
  Gain_out1 <= Gain_cast(62 DOWNTO 31);

  T_signed <= signed(T);

  Gain1_cast <= resize(T_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
  Gain1_out1 <= Gain1_cast(62 DOWNTO 31);

  y <= alphaFPGA_Part_out1;

END rtl;

