-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\uc3_preparation1_2017\hdlgenerate.vhd
-- Created: 2018-08-28 20:42:58
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: hdlgenerate
-- Source Path: uc3_preparation1_2017/CandHDL_hdl/hdlgenerate
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY hdlgenerate IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        BTN0                              :   IN    std_logic;
        BTN1                              :   IN    std_logic;
        BTN2                              :   IN    std_logic;
        BTN3                              :   IN    std_logic;
        SW0                               :   IN    std_logic;
        SW1                               :   IN    std_logic;
        SW2                               :   IN    std_logic;
        SW3                               :   IN    std_logic;
        AD6                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AD7                               :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AD14                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        AD15                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Digital_in                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        tune_w0000                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tune_w0001                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tune_w0002                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tune_w0003                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tune_w0004                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tune_w0005                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tune_w0006                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        tune_w0007                        :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig1            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig2            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig3            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig4            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig5            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig6            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig7            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig8            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig9            :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_in_sig10           :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
        LD0                               :   OUT   std_logic;
        LD1                               :   OUT   std_logic;
        LD2                               :   OUT   std_logic;
        LD3                               :   OUT   std_logic;
        duty1                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty2                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty3                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty4                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty5                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty6                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty7                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        duty8                             :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        Digital_out                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        probe_r0100                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        probe_r0101                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        probe_r0102                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        probe_r0103                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        probe_r0104                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        probe_r0105                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        probe_r0106                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        probe_r0107                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig1           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig2           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig3           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig4           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig5           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig6           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig7           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig8           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig9           :   OUT   std_logic_vector(31 DOWNTO 0);  -- int32
        shared_signals_out_sig10          :   OUT   std_logic_vector(31 DOWNTO 0)  -- int32
        );
END hdlgenerate;


ARCHITECTURE rtl OF hdlgenerate IS

  -- Component Declarations
  COMPONENT FPGA_simulation
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          M                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          T                               :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Cc0                             :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Cc1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Cc2                             :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          Count_out                       :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          we                              :   IN    std_logic_vector(31 DOWNTO 0);  -- int32
          y                               :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FPGA_simulation
    USE ENTITY work.FPGA_simulation(rtl);

  -- Signals
  SIGNAL btn1_1                           : std_logic;
  SIGNAL btn2_1                           : std_logic;
  SIGNAL btn3_1                           : std_logic;
  SIGNAL btn4                             : std_logic;
  SIGNAL sw3_1                            : std_logic;
  SIGNAL sw4                              : std_logic;
  SIGNAL Data_Type_Conversion2_out1       : std_logic;
  SIGNAL Delay_reg                        : std_logic_vector(0 TO 1);  -- ufix1 [2]
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL tune_w0000_signed                : signed(31 DOWNTO 0);  -- int32
  SIGNAL Data_Type_Conversion_out1        : std_logic;
  SIGNAL FPGA_simulation_out1             : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL TmpGroundAtduty2Inport1_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL TmpGroundAtduty3Inport1_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL TmpGroundAtduty4Inport1_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL TmpGroundAtduty5Inport1_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL TmpGroundAtduty6Inport1_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL TmpGroundAtduty7Inport1_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL TmpGroundAtduty8Inport1_out1     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL alpha8_bit_data_out1             : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Constant36_out1                  : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Bit_Concat_out1                  : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant_out1                    : signed(15 DOWNTO 0);  -- int16
  SIGNAL Data_Type_Conversion1_out1       : signed(31 DOWNTO 0);  -- int32
  SIGNAL TmpGroundAtprobe_r0103Inport1_out1 : signed(31 DOWNTO 0);  -- int32
  SIGNAL TmpGroundAtprobe_r0104Inport1_out1 : signed(31 DOWNTO 0);  -- int32
  SIGNAL TmpGroundAtprobe_r0105Inport1_out1 : signed(31 DOWNTO 0);  -- int32
  SIGNAL TmpGroundAtprobe_r0106Inport1_out1 : signed(31 DOWNTO 0);  -- int32
  SIGNAL TmpGroundAtprobe_r0107Inport1_out1 : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in2                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL Constant1_out1                   : signed(15 DOWNTO 0);  -- int16
  SIGNAL share_in3                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in4                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in5                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in6                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in7                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in8                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in9                        : signed(31 DOWNTO 0);  -- int32
  SIGNAL share_in10                       : signed(31 DOWNTO 0);  -- int32

BEGIN
  u_FPGA_simulation : FPGA_simulation
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              M => shared_signals_in_sig6,  -- int32
              T => shared_signals_in_sig7,  -- int32
              Cc0 => shared_signals_in_sig2,  -- int32
              Cc1 => shared_signals_in_sig3,  -- int32
              Cc2 => shared_signals_in_sig4,  -- int32
              Count_out => shared_signals_in_sig8,  -- int32
              we => shared_signals_in_sig5,  -- int32
              y => FPGA_simulation_out1  -- uint16
              );

  btn1_1 <= BTN0;

  btn2_1 <= BTN1;

  btn3_1 <= BTN2;

  btn4 <= BTN3;

  sw3_1 <= SW2;

  sw4 <= SW3;

  
  Data_Type_Conversion2_out1 <= '1' WHEN btn1_1 /= '0' ELSE
      '0';

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_reg(0) <= Data_Type_Conversion2_out1;
        Delay_reg(1) <= Delay_reg(0);
      END IF;
    END IF;
  END PROCESS Delay_process;

  Delay_out1 <= Delay_reg(1);

  tune_w0000_signed <= signed(tune_w0000);

  
  Data_Type_Conversion_out1 <= '1' WHEN tune_w0000_signed /= to_signed(0, 32) ELSE
      '0';

  TmpGroundAtduty2Inport1_out1 <= to_unsigned(16#0000#, 16);

  duty2 <= std_logic_vector(TmpGroundAtduty2Inport1_out1);

  TmpGroundAtduty3Inport1_out1 <= to_unsigned(16#0000#, 16);

  duty3 <= std_logic_vector(TmpGroundAtduty3Inport1_out1);

  TmpGroundAtduty4Inport1_out1 <= to_unsigned(16#0000#, 16);

  duty4 <= std_logic_vector(TmpGroundAtduty4Inport1_out1);

  TmpGroundAtduty5Inport1_out1 <= to_unsigned(16#0000#, 16);

  duty5 <= std_logic_vector(TmpGroundAtduty5Inport1_out1);

  TmpGroundAtduty6Inport1_out1 <= to_unsigned(16#0000#, 16);

  duty6 <= std_logic_vector(TmpGroundAtduty6Inport1_out1);

  TmpGroundAtduty7Inport1_out1 <= to_unsigned(16#0000#, 16);

  duty7 <= std_logic_vector(TmpGroundAtduty7Inport1_out1);

  TmpGroundAtduty8Inport1_out1 <= to_unsigned(16#0000#, 16);

  duty8 <= std_logic_vector(TmpGroundAtduty8Inport1_out1);

  alpha8_bit_data_out1 <= to_unsigned(16#1#, 4);

  Constant36_out1 <= to_unsigned(16#0#, 4);

  Bit_Concat_out1 <= alpha8_bit_data_out1 & Constant36_out1;

  Digital_out <= std_logic_vector(Bit_Concat_out1);

  Constant_out1 <= to_signed(16#014F#, 16);

  Data_Type_Conversion1_out1 <= resize(Constant_out1, 32);

  probe_r0102 <= std_logic_vector(Data_Type_Conversion1_out1);

  TmpGroundAtprobe_r0103Inport1_out1 <= to_signed(0, 32);

  probe_r0103 <= std_logic_vector(TmpGroundAtprobe_r0103Inport1_out1);

  TmpGroundAtprobe_r0104Inport1_out1 <= to_signed(0, 32);

  probe_r0104 <= std_logic_vector(TmpGroundAtprobe_r0104Inport1_out1);

  TmpGroundAtprobe_r0105Inport1_out1 <= to_signed(0, 32);

  probe_r0105 <= std_logic_vector(TmpGroundAtprobe_r0105Inport1_out1);

  TmpGroundAtprobe_r0106Inport1_out1 <= to_signed(0, 32);

  probe_r0106 <= std_logic_vector(TmpGroundAtprobe_r0106Inport1_out1);

  TmpGroundAtprobe_r0107Inport1_out1 <= to_signed(0, 32);

  probe_r0107 <= std_logic_vector(TmpGroundAtprobe_r0107Inport1_out1);

  share_in2 <= to_signed(0, 32);

  shared_signals_out_sig2 <= std_logic_vector(share_in2);

  Constant1_out1 <= to_signed(16#0401#, 16);

  share_in3 <= resize(Constant1_out1, 32);

  shared_signals_out_sig3 <= std_logic_vector(share_in3);

  share_in4 <= to_signed(0, 32);

  shared_signals_out_sig4 <= std_logic_vector(share_in4);

  share_in5 <= to_signed(0, 32);

  shared_signals_out_sig5 <= std_logic_vector(share_in5);

  share_in6 <= to_signed(0, 32);

  shared_signals_out_sig6 <= std_logic_vector(share_in6);

  share_in7 <= to_signed(0, 32);

  shared_signals_out_sig7 <= std_logic_vector(share_in7);

  share_in8 <= to_signed(0, 32);

  shared_signals_out_sig8 <= std_logic_vector(share_in8);

  share_in9 <= to_signed(0, 32);

  shared_signals_out_sig9 <= std_logic_vector(share_in9);

  share_in10 <= to_signed(0, 32);

  shared_signals_out_sig10 <= std_logic_vector(share_in10);












  LD0 <= Delay_out1;

  LD1 <= SW0;

  LD2 <= SW1;

  LD3 <= Data_Type_Conversion_out1;

  duty1 <= FPGA_simulation_out1;

  probe_r0100 <= tune_w0001;

  probe_r0101 <= shared_signals_in_sig1;

  shared_signals_out_sig1 <= tune_w0002;

END rtl;

