-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\uc3_preparation1_2017\TimeGenerator.vhd
-- Created: 2018-08-28 20:42:58
-- 
-- Generated by MATLAB 9.4 and HDL Coder 3.12
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TimeGenerator
-- Source Path: uc3_preparation1_2017/CandHDL_hdl/hdlgenerate/FPGA_simulation/TimeGenerator
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY TimeGenerator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        M                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En19
        T                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En19
        Time_rsvd                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En19
        read_add                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END TimeGenerator;


ARCHITECTURE rtl OF TimeGenerator IS

  -- Signals
  SIGNAL M_signed                         : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Constant3_out1                   : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Constant1_out1                   : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Switch_out1                      : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Unit_Delay1_out1                 : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Add1_out1                        : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL Relational_Operator_relop1_dtc   : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL T_signed                         : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Constant2_out1                   : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Product1_mul_temp                : signed(63 DOWNTO 0);  -- sfix64_En38
  SIGNAL Product1_out1                    : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Product_mul_temp                 : signed(63 DOWNTO 0);  -- sfix64_En38
  SIGNAL Time_tmp                         : signed(31 DOWNTO 0);  -- sfix32_En19
  SIGNAL Bit_Slice_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bias_const_val_1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Bias_out1                        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  M_signed <= signed(M);

  Constant3_out1 <= to_signed(67108864, 32);

  Constant1_out1 <= to_signed(0, 32);

  Unit_Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay1_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay1_out1 <= Switch_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay1_process;


  Add1_out1 <= M_signed + Unit_Delay1_out1;

  
  Relational_Operator_relop1 <= '1' WHEN Add1_out1 >= Constant3_out1 ELSE
      '0';

  Relational_Operator_relop1_dtc <= signed(resize(unsigned'(Relational_Operator_relop1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'), 32));

  
  switch_compare_1 <= '1' WHEN Relational_Operator_relop1_dtc >= to_signed(262144, 32) ELSE
      '0';

  
  Switch_out1 <= Add1_out1 WHEN switch_compare_1 = '0' ELSE
      Constant1_out1;

  T_signed <= signed(T);

  Constant2_out1 <= to_signed(2048, 32);

  Product1_mul_temp <= T_signed * Constant2_out1;
  Product1_out1 <= Product1_mul_temp(50 DOWNTO 19);

  Product_mul_temp <= Switch_out1 * Product1_out1;
  Time_tmp <= Product_mul_temp(50 DOWNTO 19);

  Time_rsvd <= std_logic_vector(Time_tmp);

  Bit_Slice_out1 <= unsigned(Switch_out1(26 DOWNTO 19));

  Bias_const_val_1 <= to_unsigned(16#01#, 8);

  Bias_out1 <= Bit_Slice_out1 + Bias_const_val_1;

  read_add <= std_logic_vector(Bias_out1);






END rtl;

