# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
# IP: The module: 'simcycle_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
# IP: The module: 'simcycle_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simcycle_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
