# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.cache/wt [current_project]
set_property parent.project_path F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/jtag_mac.v
read_vhdl -library xil_defaultlib {
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fil_test.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/fil_test_wrapper.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/jtag_mac_fifo_wrapper.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/mwfil_bus2dut.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/mwfil_chifcore.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/mwfil_chiftop.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/mwfil_controller.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/mwfil_dpscram.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/mwfil_dut2bus.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/mwfil_udfifo.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/simcycle_fifo_wrapper.vhd
  F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/fil_test_fil.vhd
}
read_ip -quiet f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo_ooc.xdc]
set_property is_locked true [get_files f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/simcycle_fifo/simcycle_fifo.xci]

read_ip -quiet f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo_ooc.xdc]
set_property is_locked true [get_files f:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/fpgaproj/fil_test_fil.srcs/sources_1/ip/jtag_mac_fifo/jtag_mac_fifo.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/fil_test_fil.xdc
set_property used_in_implementation false [get_files F:/Master_Studies/Semester_2/Model_Based_Simulation/Labs/Lab_4/Practical_work/filsrc/fil_test_fil.xdc]


synth_design -top fil_test_fil -part xc7z010clg400-1


write_checkpoint -force -noxdef fil_test_fil.dcp

catch { report_utilization -file fil_test_fil_utilization_synth.rpt -pb fil_test_fil_utilization_synth.pb }
